# Generated by Django 6.0.4 on 2026-07-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_text_resume_notes_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.resume'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_change_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_change_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
